# GolangCI-Lint configuration for GW2 MCP Server

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality
    - bodyclose
    - copyloopvar
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
    
    # Style
    - dogsled
    - funlen
    - mnd
